### ISSUE TITLE
Index page buttons shadow issue

### ISSUE THREAD

**Issue by plsthink** [yellorg/website#55]
Buttons "shadows" on index page sections (except Hero) have incorrect styling.

![a](https://user-images.githubusercontent.com/64220659/134900165-d8acf834-ba9c-4658-b79c-80d7240531e5.png)

**Comment by josadcha** [comment]
designer has updated the shadow on mockups

**Comment by josadcha** [comment]
https://openware-inc.atlassian.net/browse/SPEAR-103
